#!/usr/bin/env python3
"""Generate docs/{en,zh}/workflows.md from workflows/*.yaml manifests.

Idempotent — same input produces byte-identical output. Run via:

    python3 scripts/generate_workflow_docs.py
    python3 scripts/generate_workflow_docs.py --lang en --output docs/en/workflows.md
    python3 scripts/generate_workflow_docs.py --check   # CI: fail if regenerated output differs

The manifests in workflows/ are the canonical source. This generator is a
read-only consumer; never edit the generated docs by hand.
"""

from __future__ import annotations

import argparse
import io
import re
import sys
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Localized labels
# ---------------------------------------------------------------------------

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "page_title": "Workflows",
        "page_intro": (
            "Operational workflow manifests for the solo-trader OS. Each workflow names "
            "the exact skills, decision gates, and artifacts in order. Manifests in "
            "[`workflows/`](https://github.com/tradermonty/claude-trading-skills/tree/main/workflows) "
            "are the canonical definition; this page is auto-generated from them."
        ),
        "auto_generated_note": (
            "This page is auto-generated by `scripts/generate_workflow_docs.py`. "
            "Do not edit by hand."
        ),
        "summary_table_title": "Available workflows",
        "col_workflow": "Workflow",
        "col_cadence": "Cadence",
        "col_minutes": "Est. min",
        "col_api": "API profile",
        "col_difficulty": "Difficulty",
        "when_to_run": "When to run",
        "when_not_to_run": "When NOT to run",
        "required_skills": "Required skills",
        "optional_skills": "Optional skills",
        "prerequisite_workflows": "Prerequisite workflows (informational)",
        "prerequisite_artifact": "expects",
        "manual_inputs": "Manual input contracts",
        "col_input": "Input",
        "col_used_by_steps": "Used by steps",
        "col_schema_ref": "Schema reference",
        "col_description": "Description",
        "artifacts": "Artifacts",
        "col_artifact": "Artifact",
        "col_produced_by": "Produced by step",
        "col_required": "Required",
        "col_downstream": "Downstream hints",
        "steps": "Steps",
        "step_label": "Step",
        "step_optional": "(optional)",
        "step_decision_gate": "(decision gate)",
        "step_consumes": "consumes",
        "step_produces": "produces",
        "step_decision_question": "Decision",
        "manual_review": "Manual review",
        "journal_destination": "Journal destination",
        "final_outputs": "Final outputs",
        "yes": "yes",
        "no": "no",
        "none": "(none)",
    },
    "zh": {
        "page_title": "工作流",
        "page_intro": (
            "个人交易者操作系统的运营工作流定义。每个工作流按顺序描述"
            "使用的技能、决策关卡和产出物的流程。"
            "[`workflows/`](https://github.com/tradermonty/claude-trading-skills/tree/main/workflows) "
            "下的定义文件为权威来源，本页面由此自动生成。"
        ),
        "auto_generated_note": (
            "本页面由 `scripts/generate_workflow_docs.py` 自动生成。请勿手动编辑。"
        ),
        "summary_table_title": "工作流一览",
        "col_workflow": "工作流",
        "col_cadence": "频率",
        "col_minutes": "预计（分钟）",
        "col_api": "API 配置",
        "col_difficulty": "难度",
        "when_to_run": "执行时机",
        "when_not_to_run": "不应执行的情况",
        "required_skills": "必需技能",
        "optional_skills": "可选技能",
        "prerequisite_workflows": "前置工作流（参考信息）",
        "prerequisite_artifact": "期望的产出物",
        "manual_inputs": "手动输入契约",
        "col_input": "输入",
        "col_used_by_steps": "使用步骤",
        "col_schema_ref": "Schema 参考",
        "col_description": "说明",
        "artifacts": "产出物一览",
        "col_artifact": "产出物",
        "col_produced_by": "生成步骤",
        "col_required": "必需",
        "col_downstream": "下游提示",
        "steps": "步骤",
        "step_label": "步骤",
        "step_optional": "（可选）",
        "step_decision_gate": "（决策关卡）",
        "step_consumes": "输入",
        "step_produces": "输出",
        "step_decision_question": "决策",
        "manual_review": "手动审查",
        "journal_destination": "记录目标",
        "final_outputs": "最终输出",
        "yes": "是",
        "no": "否",
        "none": "（无）",
    },
}


ENUM_LABELS: dict[str, dict[str, dict[str, str]]] = {
    "cadence": {
        "en": {},
        "zh": {
            "daily": "每日",
            "weekly": "每周",
            "monthly": "每月",
            "ad-hoc": "临时",
        },
    },
    "difficulty": {
        "en": {},
        "zh": {
            "beginner": "初级",
            "intermediate": "中级",
            "advanced": "高级",
        },
    },
}


JEKYLL_FRONTMATTER = {
    "en": """---
layout: default
title: Workflows
parent: English
nav_order: 4
lang_peer: /zh/workflows/
permalink: /en/workflows/
---
""",
    "zh": """---
layout: default
title: 工作流
parent: 中文
nav_order: 4
lang_peer: /en/workflows/
permalink: /zh/workflows/
---
""",
}


# ---------------------------------------------------------------------------
# Workflow loading
# ---------------------------------------------------------------------------


def load_workflows(workflows_dir: Path) -> list[dict[str, Any]]:
    """Load every workflows/*.yaml as a sorted list of dicts."""
    out = []
    for path in sorted(workflows_dir.glob("*.yaml")):
        with path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if isinstance(data, dict) and data.get("id"):
            out.append(data)
    return out


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------

# CJK punctuation, kana, ideographs, and full-width forms — the character
# classes that never take an inter-character space in CJK typography.
_CJK_CHAR_CLASS = "　-〿぀-ヿ㐀-䶿一-鿿豈-﫿＀-￯"
_CJK_JOINED_SPACE = re.compile(f"(?<=[{_CJK_CHAR_CLASS}]) +(?=[{_CJK_CHAR_CLASS}])")


def _wrap(text: str | None) -> str:
    if not text:
        return ""
    # Collapse YAML folded-scalar multiline into single line
    collapsed = " ".join(text.split())
    # A YAML folded scalar joins its wrapped lines with a space. That is correct
    # for English, but CJK prose has no inter-character space, so the join
    # leaks a visible space into the middle of a sentence. Drop the space only
    # when BOTH neighbours are CJK/full-width — a space next to ASCII (an
    # inline `code` span, a latin word) is intentional and preserved.
    return _CJK_JOINED_SPACE.sub("", collapsed)


def _localized_text(
    item: dict,
    field: str,
    lang: str,
    location: str,
    *,
    default: str = "",
) -> str:
    """Resolve prose for a locale; Chinese never falls back to English."""
    if lang == "en":
        value = item.get(field, default)
        return value if isinstance(value, str) else str(value or default)

    localized_field = f"{field}_zh"
    value = item.get(localized_field)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{location}.{localized_field} must be a non-empty string")
    return value


def _localized_enum(field: str, value: object, lang: str) -> str:
    raw = str(value or "")
    return ENUM_LABELS[field][lang].get(raw, raw)


def _mapping_list(
    item: dict,
    field: str,
    location: str,
    *,
    required: bool = False,
) -> list[dict]:
    """Return a list of mappings or fail with an actionable error."""
    value = item.get(field)
    if value is None:
        if required:
            raise ValueError(f"{location}.{field} must be a list")
        return []
    if not isinstance(value, list):
        raise ValueError(f"{location}.{field} must be a list")
    for index, child in enumerate(value):
        if not isinstance(child, dict):
            raise ValueError(f"{location}.{field}[{index}] must be a mapping")
    return value


def _render_summary_table(workflows: list[dict], labels: dict[str, str], lang: str) -> str:
    buf = io.StringIO()
    buf.write(f"## {labels['summary_table_title']}\n\n")
    buf.write(
        f"| {labels['col_workflow']} | {labels['col_cadence']} | {labels['col_minutes']} | "
        f"{labels['col_api']} | {labels['col_difficulty']} |\n"
    )
    buf.write("|---|---|---|---|---|\n")
    for wf in workflows:
        wf_id = wf["id"]
        anchor = f"#{wf_id}"
        display_name = _localized_text(
            wf, "display_name", lang, f"workflows/{wf_id}", default=wf_id
        )
        cadence = _localized_enum("cadence", wf.get("cadence"), lang)
        difficulty = _localized_enum("difficulty", wf.get("difficulty"), lang)
        buf.write(
            f"| [`{wf_id}`]({anchor}) — {display_name} "
            f"| {cadence} "
            f"| {wf.get('estimated_minutes', '')} "
            f"| {wf.get('api_profile', '')} "
            f"| {difficulty} |\n"
        )
    buf.write("\n")
    return buf.getvalue()


def _render_skill_list(skills: list[str], labels: dict[str, str], heading: str) -> str:
    if not skills:
        return f"**{heading}:** {labels['none']}\n\n"
    items = ", ".join(f"`{s}`" for s in skills)
    return f"**{heading}:** {items}\n\n"


def _render_prerequisite_workflows(
    prereqs: list[dict], labels: dict[str, str], lang: str, workflow_id: str
) -> str:
    if not prereqs:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['prerequisite_workflows']}:**\n\n")
    for index, p in enumerate(prereqs):
        wf = p.get("id", "?")
        artifact = p.get("artifact", "?")
        rationale = _wrap(
            _localized_text(
                p,
                "rationale",
                lang,
                f"workflows/{workflow_id}.prerequisite_workflows[{index}]",
            )
        )
        buf.write(f"- `{wf}` {labels['prerequisite_artifact']} `{artifact}`")
        if rationale:
            buf.write(f" — {rationale}")
        buf.write("\n")
    buf.write("\n")
    return buf.getvalue()


def _render_manual_inputs(
    inputs: list[dict], labels: dict[str, str], lang: str, workflow_id: str
) -> str:
    if not inputs:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['manual_inputs']}:**\n\n")
    buf.write(
        f"| {labels['col_input']} | {labels['col_required']} | "
        f"{labels['col_used_by_steps']} | {labels['col_schema_ref']} | "
        f"{labels['col_description']} |\n"
    )
    buf.write("|---|---|---|---|---|\n")
    for index, item in enumerate(inputs):
        input_id = item.get("id", "")
        required = labels["yes"] if item.get("required", False) else labels["no"]
        steps = ", ".join(str(step) for step in (item.get("used_by_steps") or [])) or "—"
        schema_ref = item.get("schema_ref") or ""
        schema = f"`{schema_ref}`" if schema_ref else "—"
        description = (
            _wrap(
                _localized_text(
                    item,
                    "description",
                    lang,
                    f"workflows/{workflow_id}.manual_inputs[{index}]",
                )
            )
            or "—"
        )
        buf.write(f"| `{input_id}` | {required} | {steps} | {schema} | {description} |\n")
    buf.write("\n")
    return buf.getvalue()


def _render_artifacts(artifacts: list[dict], labels: dict[str, str]) -> str:
    if not artifacts:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['artifacts']}:**\n\n")
    buf.write(
        f"| {labels['col_artifact']} | {labels['col_produced_by']} | "
        f"{labels['col_required']} | {labels['col_downstream']} |\n"
    )
    buf.write("|---|---|---|---|\n")
    for art in artifacts:
        art_id = art.get("id", "")
        produced_by = art.get("produced_by_step", "")
        required = labels["yes"] if art.get("required", False) else labels["no"]
        downstream = art.get("downstream_hints") or []
        downstream_str = ", ".join(f"`{w}`" for w in downstream) if downstream else "—"
        buf.write(f"| `{art_id}` | {produced_by} | {required} | {downstream_str} |\n")
    buf.write("\n")
    return buf.getvalue()


def _render_step(
    step: dict,
    labels: dict[str, str],
    lang: str,
    workflow_id: str,
    step_index: int,
) -> str:
    buf = io.StringIO()
    step_num = step.get("step", "?")
    location = f"workflows/{workflow_id}.steps[{step_index}]"
    name = _localized_text(step, "name", lang, location)
    skill = step.get("skill", "?")
    flags = []
    if step.get("optional"):
        flags.append(labels["step_optional"])
    if step.get("decision_gate"):
        flags.append(labels["step_decision_gate"])
    flag_str = f" {' '.join(flags)}" if flags else ""

    buf.write(f"**{labels['step_label']} {step_num}: {name}**{flag_str} → `{skill}`\n\n")

    consumes = step.get("consumes") or []
    produces = step.get("produces") or []
    if consumes:
        buf.write(f"- {labels['step_consumes']}: " + ", ".join(f"`{c}`" for c in consumes) + "\n")
    if produces:
        buf.write(f"- {labels['step_produces']}: " + ", ".join(f"`{p}`" for p in produces) + "\n")
    if step.get("decision_gate"):
        q = _wrap(_localized_text(step, "decision_question", lang, location))
        if q:
            buf.write(f"- **{labels['step_decision_question']}:** {q}\n")

    buf.write("\n")
    return buf.getvalue()


def _render_manual_review(items: list[str] | None, labels: dict[str, str]) -> str:
    if not items:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['manual_review']}:**\n\n")
    for item in items:
        buf.write(f"- {item}\n")
    buf.write("\n")
    return buf.getvalue()


def _render_final_outputs(
    items: list[dict] | None,
    labels: dict[str, str],
    lang: str,
    workflow_id: str,
) -> str:
    if not items:
        return ""
    buf = io.StringIO()
    buf.write(f"**{labels['final_outputs']}:**\n\n")
    for index, item in enumerate(items):
        if isinstance(item, dict):
            iid = item.get("id", "")
            desc = _localized_text(
                item,
                "description",
                lang,
                f"workflows/{workflow_id}.final_outputs[{index}]",
            )
            buf.write(f"- `{iid}` — {desc}\n" if desc else f"- `{iid}`\n")
        else:
            buf.write(f"- `{item}`\n")
    buf.write("\n")
    return buf.getvalue()


def render_workflow_section(wf: dict, labels: dict[str, str], lang: str) -> str:
    buf = io.StringIO()
    wf_id = wf["id"]
    workflow_location = f"workflows/{wf_id}"
    display_name = _localized_text(wf, "display_name", lang, workflow_location, default=wf_id)
    cadence = _localized_enum("cadence", wf.get("cadence"), lang)
    difficulty = _localized_enum("difficulty", wf.get("difficulty"), lang)
    minutes = wf.get("estimated_minutes", "?")
    duration = f"~{minutes} min" if lang == "en" else f"约{minutes}分钟"

    buf.write(f"## {display_name} {{#{wf_id}}}\n\n")
    buf.write(
        f"**`{wf_id}`** · {cadence} · {duration} · {wf.get('api_profile', '')} · {difficulty}\n\n"
    )

    when_to = _wrap(_localized_text(wf, "when_to_run", lang, workflow_location))
    when_not = _wrap(_localized_text(wf, "when_not_to_run", lang, workflow_location))
    if when_to:
        buf.write(f"**{labels['when_to_run']}:** {when_to}\n\n")
    if when_not:
        buf.write(f"**{labels['when_not_to_run']}:** {when_not}\n\n")

    buf.write(
        _render_skill_list(wf.get("required_skills") or [], labels, labels["required_skills"])
    )
    buf.write(
        _render_skill_list(wf.get("optional_skills") or [], labels, labels["optional_skills"])
    )
    prerequisites = _mapping_list(wf, "prerequisite_workflows", workflow_location)
    manual_inputs = _mapping_list(wf, "manual_inputs", workflow_location)
    steps = _mapping_list(wf, "steps", workflow_location, required=True)
    final_outputs = _mapping_list(wf, "final_outputs", workflow_location)
    buf.write(_render_prerequisite_workflows(prerequisites, labels, lang, wf_id))
    buf.write(_render_manual_inputs(manual_inputs, labels, lang, wf_id))
    buf.write(_render_artifacts(wf.get("artifacts") or [], labels))

    if steps:
        buf.write(f"**{labels['steps']}:**\n\n")
        for index, step in enumerate(steps):
            buf.write(_render_step(step, labels, lang, wf_id, index))

    if lang == "zh":
        source_review = wf.get("manual_review")
        if not isinstance(source_review, list):
            raise ValueError(f"{workflow_location}.manual_review must be a list")
        manual_review = wf.get("manual_review_zh")
        if not isinstance(manual_review, list):
            raise ValueError(f"{workflow_location}.manual_review_zh must be a list")
        expected_count = len(source_review)
        if len(manual_review) != expected_count:
            raise ValueError(
                f"{workflow_location}.manual_review_zh must contain exactly "
                f"{expected_count} item(s) to match manual_review"
            )
        for index, item in enumerate(manual_review):
            if not isinstance(item, str) or not item.strip():
                raise ValueError(
                    f"{workflow_location}.manual_review_zh[{index}] must be a non-empty string"
                )
    else:
        manual_review = wf.get("manual_review")
    buf.write(_render_manual_review(manual_review, labels))
    buf.write(_render_final_outputs(final_outputs, labels, lang, wf_id))

    journal = wf.get("journal_destination")
    if journal:
        buf.write(f"**{labels['journal_destination']}:** `{journal}`\n\n")

    buf.write("---\n\n")
    return buf.getvalue()


def render_page(workflows: list[dict], lang: str) -> str:
    labels = LABELS[lang]
    buf = io.StringIO()
    buf.write(JEKYLL_FRONTMATTER[lang])
    buf.write(f"\n# {labels['page_title']}\n")
    buf.write("{: .no_toc }\n\n")
    buf.write(f"> _{labels['auto_generated_note']}_\n\n")
    buf.write(f"{labels['page_intro']}\n\n")
    buf.write("---\n\n")
    buf.write(_render_summary_table(workflows, labels, lang))
    buf.write("---\n\n")
    for wf in workflows:
        buf.write(render_workflow_section(wf, labels, lang))
    # Normalize trailing newlines to a single \n so generator output stays
    # in lockstep with the end-of-file-fixer pre-commit hook. Otherwise
    # --check would always drift after the fixer trims the page.
    return buf.getvalue().rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def default_output_path(project_root: Path, lang: str) -> Path:
    return project_root / "docs" / lang / "workflows.md"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate docs/{en,zh}/workflows.md from workflows/*.yaml manifests."
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Path to the repository root (default: cwd)",
    )
    parser.add_argument(
        "--lang",
        choices=["en", "zh", "all"],
        default="all",
        help="Which language to generate (default: all)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Override output path (only valid with --lang en or --lang zh)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare regenerated output against on-disk files; exit non-zero if they differ.",
    )
    args = parser.parse_args(argv)

    if args.output and args.lang == "all":
        print("--output requires --lang en or --lang zh, not all", file=sys.stderr)
        return 2

    workflows_dir = args.project_root / "workflows"
    if not workflows_dir.is_dir():
        print(f"ERROR: {workflows_dir} not found", file=sys.stderr)
        return 1

    workflows = load_workflows(workflows_dir)
    if not workflows:
        print(f"ERROR: no workflow manifests found under {workflows_dir}", file=sys.stderr)
        return 1

    langs = ["en", "zh"] if args.lang == "all" else [args.lang]
    drift = False

    for lang in langs:
        try:
            rendered = render_page(workflows, lang)
        except ValueError as exc:
            print(f"ERROR: workflow localization is incomplete: {exc}", file=sys.stderr)
            return 1
        target = args.output or default_output_path(args.project_root, lang)

        if args.check:
            if not target.is_file():
                print(f"DRIFT: {target} does not exist", file=sys.stderr)
                drift = True
                continue
            existing = target.read_text(encoding="utf-8")
            if existing != rendered:
                print(f"DRIFT: {target} differs from regenerated output", file=sys.stderr)
                drift = True
            else:
                print(f"OK: {target} matches", file=sys.stderr)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(rendered, encoding="utf-8")
            print(f"Wrote {target} ({len(workflows)} workflows)", file=sys.stderr)

    return 1 if (args.check and drift) else 0


if __name__ == "__main__":
    raise SystemExit(main())
